version: "3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ../docs/swagger.json:/swagger.json
    environment:
      - SWAGGER_JSON=/swagger.json
