version: "3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./swagger.json:/foo/swagger.json
    environment:
      - SWAGGER_JSON=/foo/swagger.json
